# Generated by Django 3.2.16 on 2022-10-16 18:32

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='full_name')),
                ('full_name', models.CharField(max_length=150, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('employment_date', models.DateField(null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='structure.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
